SAVE_DIR = ".temp_classifier"
SAVE_FILE = SAVE_DIR + "/" + "features.csv"
FORBIDDEN_CHARS = r'[\\/:*?"<>|]' #Not allowed in windows file names

HINT_TEXT = {
    "program_start": "Hover over an element to get an explanation",
    "load_file_button": "Click to select the audio file(s) you wish to classify",
    "load_csv_file_button": "Click to select a pre-extracted feature list",
    "load_folder_button": "Click to select a folder containing the audio files you wish to classify",
    "extract_button": "Click to begin extracting features from the selected files",
    "save_button": "Click to save the extracted features to a specified location",
    "file_path_label": "Shows the selected file path",
    "progress_label": "Shows the progress on the currently running process",
    "hint_label": "Shows helpful hints"
}

HEADER = (
    'filename',
    'length',
    'chroma_stft_mean',
    'chroma_stft_var',
    'rms_mean',
    'rms_var',
    'spectral_centroid_mean',
    'spectral_centroid_var',
    'spectral_bandwidth_mean',
    'spectral_bandwidth_var',
    'rolloff_mean',
    'rolloff_var',
    'zero_crossing_rate_mean',
    'zero_crossing_rate_var',
    'harmony_mean',
    'harmony_var',
    'perceptr_mean',
    'perceptr_var',
    'tempo',
    'mfcc1_mean',
    'mfcc1_var',
    'mfcc2_mean',
    'mfcc2_var',
    'mfcc3_mean',
    'mfcc3_var',
    'mfcc4_mean',
    'mfcc4_var',
    'mfcc5_mean',
    'mfcc5_var',
    'mfcc6_mean',
    'mfcc6_var',
    'mfcc7_mean',
    'mfcc7_var',
    'mfcc8_mean',
    'mfcc8_var',
    'mfcc9_mean',
    'mfcc9_var',
    'mfcc10_mean',
    'mfcc10_var',
    'mfcc11_mean',
    'mfcc11_var',
    'mfcc12_mean',
    'mfcc12_var',
    'mfcc13_mean',
    'mfcc13_var',
    'mfcc14_mean',
    'mfcc14_var',
    'mfcc15_mean',
    'mfcc15_var',
    'mfcc16_mean',
    'mfcc16_var',
    'mfcc17_mean',
    'mfcc17_var',
    'mfcc18_mean',
    'mfcc18_var',
    'mfcc19_mean',
    'mfcc19_var',
    'mfcc20_mean',
    'mfcc20_var',
    'label'
)

OVERWRITE_FAILED_MSG = "Failed to save the file, as the file you're trying to overwrite is likely opened already. Close the file before trying again!"
NO_DATA_MSG = "No data to save, extract some files first!"
NO_FILES_MSG = "No files selected, select some files to extract the features from first!"
