/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119925-g7039a37e35-20250620"
#endif /* AVUTIL_FFVERSION_H */
